### ISSUE TITLE
Named namespaces

### ISSUE THREAD

**Issue by planetA** [vishvananda/netns#26]
Hello,

is there a way to create a named network namespace? I mean the one that I can see in `ip netns`.

**Comment by damongant** [comment]
We do this manually right now, here's the code:

```
        if err := syscall.Unshare(syscall.CLONE_NEWNET); err != nil {
                panic(err)
        }
        p := path.Join("/var/run/netns/", netname)
        f, err := os.OpenFile(p, os.O_CREATE | os.O_EXCL, 0444)
        if err != nil {
                panic(err)
        }
        f.Close()
        if err := syscall.Mount(fmt.Sprintf("/proc/self/ns/net"), p, "bind", syscall.MS_BIND, ""); err != nil {
                panic(err)
        }
```

Should probably clean this up and submit a PR; maintainers, would you be interested in this?

**Comment by planetA** [comment]
"self/ns/net" may refer to another thread. You should access namespace
bound to your task id. I'll send full example later

**Comment by planetA** [comment]
I create a named one like this:

```golang
newNsPath := "/var/run/netns"
nsPath := fmt.Sprintf("/proc/%d/task/%d/ns/net", os.Getpid(), syscall.Gettid())
err = syscall.Mount(nsPath, newNsPath, "", syscall.MS_BIND|syscall.MS_REC, "")
```

**Comment by damongant** [comment]
Ah, that's good to know, we spawned a new process to avoid this (also because it "burns" an OS thread available to the runtime)

**Comment by jeffwidman** [comment]
I think this is now fixed?
* https://github.com/vishvananda/netns/pull/42
