### ISSUE TITLE
Nesting go routines in namespace

### ISSUE THREAD

**Issue by ic2hrmk** [vishvananda/netns#36]
Hi!

I'm looking for a way to safely separate go routines in net namespaces (see the draw below).

![Routine Separation Diagram](https://user-images.githubusercontent.com/11685484/60240485-b8e68e80-98b9-11e9-8278-d4f1dce31961.png)
 
One of my projects requires go routines to run (execute methods, not just call binaries) in different network namespaces without affecting other's routine's namespaces. For example, if one of routine calls SetNS, all routines spawned from it have to be in the same namespace as their master routine. 

Since scheduler is not under our control, there is a potential risk to switch routines on same thread to unexpected namespace which moves whole program to faulty state.

Is there a way to make namespace switching safe surrounding and predictable for routines?

**Comment by tv42** [comment]
That doesn't seem like something Go reasonably offers (at this time). I'd suggest using multiple processes, as a workaround.

Even if you were to `runtime.LockOSThread` `B`, that says nothing about `B1`, `B2`, `B3`, etc, and libraries can start goroutines behind your back too -- and worse, a library may use a pool of worker goroutines shared across your colored boxes.

**Comment by ic2hrmk** [comment]
Hi @tv42! Thank you for the response. The project where this trick was required is ended up 6 months ago :)
A few words about `runtime.LockOSThread`, from some Go version (honestly I don't remember) there was a change in scheduler that assures that no new routines would be attached to the thread if routine called `runtime.LockOSThread` until UnlockOSThread is called too (https://golang.org/pkg/runtime/#LockOSThread).

From my own experience, I hadn't a situation from what I tried to secure

**Comment by ic2hrmk** [comment]
Just found the thing what I was talking about -> https://github.com/vishvananda/netns/pull/30

**Comment by tv42** [comment]
@ic2hrmk So, given how Go is unlikely to support the model you asked for (without operating system help via multiple processes, in which case no Go support is needed), and even your need for such a thing is long gone, can this issue be closed?

**Comment by ic2hrmk** [comment]
@tv42 , yes, I think there is nothing left to discuss
