### ISSUE TITLE
Release, for go mod support

### ISSUE THREAD

**Issue by spellr** [vishvananda/netns#39]
Please release a github version, so netns will appear in go.mod with a version number

**Comment by dmitris** [comment]
+1, would help to have a "nice" `v<n>.<x>.<y>` version string instead of `v0.0.0-20180720170159-13995c7128cc` in our go.mod files 😄

**Comment by thomas-maurice** [comment]
+1

**Comment by jeffwidman** [comment]
I just got added as a maintainer, and will try to cut a release soon. I'm going to wait a few days to see if #52 can get rebased/fix merge conflicts and then merged first though.

Please remind me in a few weeks if I happen to forget.

**Comment by jeffwidman** [comment]
Just tagged https://github.com/vishvananda/netns/releases/tag/v0.0.1
