### ISSUE TITLE
Is  there any possibility to use different namespace in different goroutines?

### ISSUE THREAD

**Issue by Andy-0205** [vishvananda/netns#60]

**Comment by chkp-rigor** [comment]
I think it can be done, as long as you execute `runtime.LockOSThread()` in these goroutines. From the point you lock - no other goroutine can run on in the same OS thread.
Though worked with this 2 years ago, hopefully I didn't forget anything relevant.

**Comment by jeffwidman** [comment]
Thanks @chkp-rigor !
